wallpaper {
           monitor = eDP-1
	   path = /home/almonds/wallpaper/painting.jpg
	   fit_mode = cover
}

#wallpaper {
 #   monitor = eDP-1 
  #  path = /home/noosphere/wallpaper/flowerwords.jpg
   # fit_mode = cover
 # }




